{% set name = "types-PyYAML" %}
{% set version = "6.0.12.20260815" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-','_') | lower }}-{{ version }}.tar.gz
  sha256: 28764110c9cf35846e733da32d8d734df7473c5dde9ef67c3b7332ec0e819858

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - setuptools >=82.0.1
  run:
    - python

test:
  imports:
    - types
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/yaml-stubs/__init__.pyi  # [unix]

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for PyYAML
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  description: |
    This is a PEP 561 type stub package for the PyYaml package.
    It can be used by type-checking tools like mypy, pyright, pytype,
    PyCharm, etc. to check code that uses PyYaml.
  dev_url: https://github.com/python/typeshed
  doc_url: https://pyyaml.org/wiki/PyYAMLDocumentation

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
